name: run-shell

on:
  push:
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo $pwd
          cd ..
          cd ..
          chmod 775 ls-script.sh
          sh ls-script.sh
