name: run-shell

on:
  push:
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: |
          pwd
          cd ..
          chmod 775 ls-script.sh
          ./ls-script.sh
